version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masivTest
    environment:
      - REDIS_HOST=172.17.0.1
    depends_on:
      - db
    ports:
    - "8080:8080"
  db:
    image: redis:latest
    container_name: db
    volumes:
    - redisdata:/data
    ports:
    - 6379:6379
volumes:
  redisdata: